# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"moving_avg": "00_moving_avg.ipynb",
         "mad": "00_moving_avg.ipynb",
         "mse": "00_moving_avg.ipynb",
         "rmse": "00_moving_avg.ipynb",
         "mape": "00_moving_avg.ipynb",
         "cumulative_error": "00_moving_avg.ipynb",
         "change_in_variable": "00_moving_avg.ipynb",
         "change_in_forecast": "00_moving_avg.ipynb",
         "turning_point_graph": "00_moving_avg.ipynb",
         "plot_data": "01_data_transformation.ipynb"}

modules = ["moving_avg.py",
           "data_transformation.py"]

doc_url = "https://YichengShen.github.io/forecast/"

git_url = "https://github.com/YichengShen/forecast/tree/main/"

def custom_doc_links(name): return None
